### ISSUE TITLE
CODE RUB: Update Image Link To Be Markdown

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#138]

**Comment by ElbekDeveloper** [comment]
https://www.markdownguide.org/basic-syntax/

**Comment by glhays** [comment]
@ElbekDeveloper 
I believe the issue here is in the parser Nuget is using to render out html from the readme markdown. Everything works fine in the git repository as is. Everyone knows this already.

I think that the div tag is what the parser is not liking.
In review of these links here:
[CommonMark Spec](https://spec.commonmark.org/0.29/#images)
[Add a Readme - Markdown and Image Support](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/)

This code change replacing div with the paragraph tag works seen here.
The break tag can be removed as the default paragraph tag includes some default padding.

`<p align=center>
	<img width="300" src="https://raw.githubusercontent.com/hassanhabib/OpenAI.NET /main/Standard.AI.OpenAI/artificial-intelligence.png" />
<p>`

In my reading of the doc's as long as the images are from a trusted site they are rendered, which raw.githubusercontent.com is.

I am not sure how this can be tested outside a new Nuget publish????? @hassanhabib Thoughts....

**Comment by hassanhabib** [comment]
@glhays we can test it without publishing - but we have to *pretend* that we are about to publish something

**Comment by glhays** [comment]
@hassanhabib / @ElbekDeveloper 
I have spent a few hours here today trying different approaches on a mock library and test publishing to nuget without any successful results. I am at a loss for the day. If someone can point to a package on nuget, man that would be helpful. I have not found one yet but then again 322k+ to look through I barely touched the surface.
